apiVersion: v1
kind: Pod
metadata:
  labels:
    probe: readiness
  name: readiness-probe
spec:
  containers:
  - name: readiness
    image: rbinrais/healthprobe:1.0
    readinessProbe:
      httpGet:
        path: /api/healthcheck
        port: 80
        httpHeaders:
        - name: X-Custom-Header
          value: NotUsedInThisExample
      initialDelaySeconds: 30
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30101
  selector:
    probe: readiness
  type: NodePort
