apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
  - name: healthprobe
    image: rbinrais/healthprobe
    readinessProbe:
      httpGet:
        path: /api/healthcheck
        port: 80
        httpHeaders:
        - name: X-Custom-Header
          value: NotUsedInThisExample
      initialDelaySeconds: 5
      periodSeconds: 5
